version: '3.7'

services:
  vue_app:
    container_name: vue_app
    build:
      context: .
      dockerfile: Dockerfile
    image: vue_app:0.0.2
    volumes:
      - '.:/vue-app'
      - '/vue-app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true